spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migration: true

  jpa:
    open-in-view: false

  profile:
    active: dev

server:
  port: 9091
  servlet:
    context-path: /api/v1